### ISSUE TITLE
调用显示：This dependency was not found:  * @w6s/sdk in ./src/main.js

### ISSUE THREAD

**Issue by felibq** [WorkPlusFE/js-sdk#14]
package.json
`
"devDependencies": {
    .....
    "@w6s/sdk": "^1.0.0-alpha.4",
    .....
  },
`
main.js
`
import Vue from 'vue'
import App from './App'
import * as w6s from "@w6s/sdk"
console.log(w6s);
Vue.config.productionTip = false

App.mpType = 'app'

const app = new Vue({
  ...App
})
app.$mount()
`
console
___________________
 ERROR  Failed to compile with 1 errors                                                                                    19:31:20

This dependency was not found:

* @w6s/sdk in ./src/main.js

To install it, you can run: npm install --save @w6s/sdk

**Comment by hejianxian** [comment]
已修复，请安装`1.0.1-alpha.0`版本。
